name: Build and push Docker image to dockerhub
on:
  push:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4
    - name: Login to dockerhub
      uses: docker/login-action@v3
      with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: build image
        run: |
          docker build . -t jrubenrm/docker-app:latest
      - name: push image to docker hub
        run: |
          docker push jrubenrm/docker-app:latest
